/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author chen
 */
public class HomeProfe extends javax.swing.JFrame {

    /**
     * Creates new form HomeProfe
     */
    public HomeProfe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu3 = new javax.swing.JPanel();
        jbAltaProfesor3 = new javax.swing.JButton();
        jbAltaAlumnos3 = new javax.swing.JButton();
        jlPerfil3 = new javax.swing.JLabel();
        jlClose3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAsignatura = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu3.setBackground(new java.awt.Color(12, 204, 144));
        menu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAltaProfesor3.setBackground(new java.awt.Color(155, 236, 164));
        jbAltaProfesor3.setForeground(new java.awt.Color(102, 102, 102));
        jbAltaProfesor3.setText("Lista");
        jbAltaProfesor3.setBorder(null);
        jbAltaProfesor3.setBorderPainted(false);
        jbAltaProfesor3.setFocusable(false);
        menu3.add(jbAltaProfesor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, 30));

        jbAltaAlumnos3.setBackground(new java.awt.Color(155, 236, 164));
        jbAltaAlumnos3.setForeground(new java.awt.Color(102, 102, 102));
        jbAltaAlumnos3.setText("Nota");
        jbAltaAlumnos3.setBorder(null);
        jbAltaAlumnos3.setBorderPainted(false);
        jbAltaAlumnos3.setFocusable(false);
        menu3.add(jbAltaAlumnos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 110, 30));

        jlPerfil3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_Male_48px_2.png"))); // NOI18N
        menu3.add(jlPerfil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jlClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Close_Window_20px_1.png"))); // NOI18N
        jlClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClose3MouseClicked(evt);
            }
        });
        menu3.add(jlClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 20));

        getContentPane().add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listAsignatura.setBackground(new java.awt.Color(255, 255, 255));
        listAsignatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        listAsignatura.setForeground(new java.awt.Color(0, 0, 0));
        listAsignatura.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "IOS", "Programacion", "Sistema", "Diseño", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listAsignatura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listAsignatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAsignaturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listAsignatura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 520, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlClose3MouseClicked

    private void listAsignaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAsignaturaMouseClicked
        String asignatura = listAsignatura.getSelectedValue();
        NotaAlumno n = new NotaAlumno(this, rootPaneCheckingEnabled, asignatura);
        n.setLocationRelativeTo(null);
        n.setVisible(true);

    }//GEN-LAST:event_listAsignaturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeProfe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaAlumnos;
    private javax.swing.JButton jbAltaAlumnos1;
    private javax.swing.JButton jbAltaAlumnos2;
    private javax.swing.JButton jbAltaAlumnos3;
    private javax.swing.JButton jbAltaProfesor;
    private javax.swing.JButton jbAltaProfesor1;
    private javax.swing.JButton jbAltaProfesor2;
    private javax.swing.JButton jbAltaProfesor3;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlClose1;
    private javax.swing.JLabel jlClose2;
    private javax.swing.JLabel jlClose3;
    private javax.swing.JLabel jlPerfil;
    private javax.swing.JLabel jlPerfil1;
    private javax.swing.JLabel jlPerfil2;
    private javax.swing.JLabel jlPerfil3;
    private javax.swing.JList<String> listAsignatura;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    // End of variables declaration//GEN-END:variables
}
