/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.PepitaDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import model.Asignatura;
import static proyectopepita.ProyectoPepita.usuarioLogeado;

/**
 *
 * @author chen
 */
public class HomeProfe extends javax.swing.JFrame {

    PepitaDAO pepitaDAO = new PepitaDAO();
    

    /**
     * Creates new form HomeProfe
     */
    public HomeProfe() throws SQLException {
        pepitaDAO.conectToBBDD();
        DefaultListModel dml = new DefaultListModel();
        List<Asignatura> listaAsignatura = pepitaDAO.listAsignaturaByProfesor(usuarioLogeado);
        for(Asignatura a : listaAsignatura){
            dml.addElement(a.getNombre());
        }
        jlistAsignatura.setModel(dml);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistAsignatura = new javax.swing.JList<>();
        jbAltaProfesor3 = new javax.swing.JButton();
        jlClose3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlistAsignatura.setBackground(new java.awt.Color(255, 255, 255));
        jlistAsignatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlistAsignatura.setForeground(new java.awt.Color(0, 0, 0));
        jlistAsignatura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistAsignatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistAsignaturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlistAsignatura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 920, 370));

        jbAltaProfesor3.setBackground(new java.awt.Color(155, 236, 164));
        jbAltaProfesor3.setForeground(new java.awt.Color(255, 255, 255));
        jbAltaProfesor3.setText("Asignaturas");
        jbAltaProfesor3.setBorder(null);
        jbAltaProfesor3.setBorderPainted(false);
        jbAltaProfesor3.setFocusable(false);
        jPanel1.add(jbAltaProfesor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, 30));

        jlClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Close_Window_20px_1.png"))); // NOI18N
        jlClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClose3MouseClicked(evt);
            }
        });
        jPanel1.add(jlClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlClose3MouseClicked

    private void jlistAsignaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistAsignaturaMouseClicked
        String asignatura = jlistAsignatura.getSelectedValue();
        NotaAlumno n = new NotaAlumno(this, rootPaneCheckingEnabled, asignatura);
        n.setLocationRelativeTo(null);
        n.setVisible(true);

    }//GEN-LAST:event_jlistAsignaturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomeProfe().setVisible(true);
                } catch (SQLException ex) {
                      System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaProfesor3;
    private javax.swing.JLabel jlClose3;
    private javax.swing.JList<String> jlistAsignatura;
    // End of variables declaration//GEN-END:variables
}
