/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.PepitaDAO;
import java.awt.event.KeyEvent;
//import excepciones.ExcepcionPepita;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyectopepita.ProyectoPepita;
import static proyectopepita.ProyectoPepita.usuarioLogeado;

/**
 *
 * @author chen
 */
public class Login extends javax.swing.JFrame {

    PepitaDAO pepitaDAO = new PepitaDAO();

    /**
     * Creates new form Login
     */
    public Login() throws SQLException {
        pepitaDAO.conectToBBDD();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/image/MINILOGO.png")).getImage());
        // PlaceHolder holder = new PlaceHolder(tuCampoDeText, "lo que quieras que se muestre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        jfPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtfEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfEmail.setForeground(new java.awt.Color(0, 0, 0));
        jtfEmail.setToolTipText("");
        jtfEmail.setBorder(null);
        jtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEmailKeyPressed(evt);
            }
        });
        jPanel2.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 200, 20));

        jLabel1.setBackground(new java.awt.Color(12, 112, 84));
        jLabel1.setForeground(new java.awt.Color(12, 112, 84));
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 112, 84), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        jLabel2.setBackground(new java.awt.Color(12, 112, 84));
        jLabel2.setForeground(new java.awt.Color(12, 112, 84));
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 112, 84), 2));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, -1));

        jbLogin.setBackground(new java.awt.Color(12, 112, 84));
        jbLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbLogin.setText("Login");
        jbLogin.setBorder(null);
        jbLogin.setBorderPainted(false);
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Close_Window_20px_1.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));

        jfPassword.setBackground(new java.awt.Color(255, 255, 255));
        jfPassword.setForeground(new java.awt.Color(0, 0, 0));
        jfPassword.setBorder(null);
        jfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(jfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 40, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        login();
    }//GEN-LAST:event_jbLoginActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        try {
            pepitaDAO.closeConection();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void jfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jfPasswordKeyPressed

    private void jtfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jtfEmailKeyPressed

    public void login() {
        String email = jtfEmail.getText();
        char[] arrayC = jfPassword.getPassword();
        String password = new String(arrayC);
        try {
            if (email.equals("") || password.equals("")) {
                showErrorMessage("Debes introducir datos");
            } else if (pepitaDAO.validateUser(email, password)) {
                if (pepitaDAO.getTypeEmail(email) == 0) {
                    pepitaDAO.closeConection();
                    usuarioLogeado = email;
                    this.setVisible(false);
                    HomeAdmin h = new HomeAdmin();
                    h.setLocationRelativeTo(null);
                    h.setVisible(true);
                } else if (pepitaDAO.getTypeEmail(email) == 1) {
                    pepitaDAO.closeConection();
                    this.setVisible(false);
                    HomeProfe h = new HomeProfe();
                    h.setLocationRelativeTo(null);
                    h.setVisible(true);
                }
            } else {
                showErrorMessage("Usuario incorrecto");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public void showErrorMessage(String message) {
        ImageIcon icon = new ImageIcon("C:\\Users\\chen\\Google Drive\\ProyectoFinal\\ProyectoNuevo\\ProyectoPepita\\src\\images\\icons8_Error_50px.png");
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.WARNING_MESSAGE, icon);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbLogin;
    private javax.swing.JPasswordField jfPassword;
    private javax.swing.JTextField jtfEmail;
    // End of variables declaration//GEN-END:variables

 
}
